<?php

add_filter( 'vc_iconpicker-type-theme-icons', 'scp_theme_icons' );

function scp_theme_icons( $icons ) {

	return array_merge( $icons, scp_get_theme_icon_list() );
}


function scp_get_theme_icon_list() {

	// http://regexr.com/

	// class="(icon-\S+)\b" regex
	// .(icon-\S+)\b: regex (copy css for icons)
	// array('$1' => '$1'),\n format

	$theme_icons = array(
		array('icon-edsuiteic_audiotrack_black_24px' => 'icon-edsuiteic_audiotrack_black_24px'),
		array('icon-edsuiteic_format_quote_black_24px' => 'icon-edsuiteic_format_quote_black_24px'),
		array('icon-edsuiteic_home_black' => 'icon-edsuiteic_home_black'),
		array('icon-edsuiteic_queue_music_black' => 'icon-edsuiteic_queue_music_black'),
		array('icon-edsuiteic_trending_up_black' => 'icon-edsuiteic_trending_up_black'),
		array('icon-edsuiteic_wb_incandescent_black' => 'icon-edsuiteic_wb_incandescent_black'),
		array('icon-edsuitequote' => 'icon-edsuitequote'),
		array('icon-edsuitearrow' => 'icon-edsuitearrow'),
		array('icon-edsuiteright-arrow' => 'icon-edsuiteright-arrow'),
		array('icon-edsuiteclock-one' => 'icon-edsuiteclock-one'),
		array('icon-edsuitecomment' => 'icon-edsuitecomment'),
		array('icon-edsuitecomputer' => 'icon-edsuitecomputer'),
		array('icon-edsuitecup' => 'icon-edsuitecup'),
		array('icon-edsuitecustomer' => 'icon-edsuitecustomer'),
		array('icon-edsuitedark-eye' => 'icon-edsuitedark-eye'),
		array('icon-edsuitediploma' => 'icon-edsuitediploma'),
		array('icon-edsuitediploma-one' => 'icon-edsuitediploma-one'),
		array('icon-edsuiteedit-draw-pencil' => 'icon-edsuiteedit-draw-pencil'),
		array('icon-edsuitefood5' => 'icon-edsuitefood5'),
		array('icon-edsuitefootball' => 'icon-edsuitefootball'),
		array('icon-edsuitegps' => 'icon-edsuitegps'),
		array('icon-edsuitehand' => 'icon-edsuitehand'),
		array('icon-edsuitehtml' => 'icon-edsuitehtml'),
		array('icon-edsuiteicon' => 'icon-edsuiteicon'),
		array('icon-edsuiteleft-arrow' => 'icon-edsuiteleft-arrow'),
		array('icon-edsuiteletter' => 'icon-edsuiteletter'),
		array('icon-edsuitelight-bulb' => 'icon-edsuitelight-bulb'),
		array('icon-edsuitemeasuring' => 'icon-edsuitemeasuring'),
		array('icon-edsuitemedal' => 'icon-edsuitemedal'),
		array('icon-edsuitemedal-number-one' => 'icon-edsuitemedal-number-one'),
		array('icon-edsuitemedal-one' => 'icon-edsuitemedal-one'),
		array('icon-edsuitemegaphone' => 'icon-edsuitemegaphone'),
		array('icon-edsuitemusic' => 'icon-edsuitemusic'),
		array('icon-edsuitenotification-bell' => 'icon-edsuitenotification-bell'),
		array('icon-edsuitepencil' => 'icon-edsuitepencil'),
		array('icon-edsuiteplaceholder' => 'icon-edsuiteplaceholder'),
		array('icon-edsuiteicon-bus' => 'icon-edsuiteicon-bus'),
		array('icon-edsuiteschool-flag' => 'icon-edsuiteschool-flag'),
		array('icon-edsuitequality' => 'icon-edsuitequality'),
		array('icon-edsuiteuniversity-flag' => 'icon-edsuiteuniversity-flag'),
		array('icon-edsuiteribbon' => 'icon-edsuiteribbon'),
		array('icon-edsuiteribbon-badge-award' => 'icon-edsuiteribbon-badge-award'),
		array('icon-edsuiteright-arrow2' => 'icon-edsuiteright-arrow2'),
		array('icon-edsuiteuniversity-campus' => 'icon-edsuiteuniversity-campus'),
		array('icon-edsuitesaturn-rings' => 'icon-edsuitesaturn-rings'),
		array('icon-edsuiteuniversity-with-a-flag' => 'icon-edsuiteuniversity-with-a-flag'),
		array('icon-edsuitearrow-pointing-to-right' => 'icon-edsuitearrow-pointing-to-right'),
		array('icon-edsuiteschool' => 'icon-edsuiteschool'),
		array('icon-edsuitescissors' => 'icon-edsuitescissors'),
		array('icon-edsuitesearch' => 'icon-edsuitesearch'),
		array('icon-edsuiteshape' => 'icon-edsuiteshape'),
		array('icon-edsuitebig-map-placeholder' => 'icon-edsuitebig-map-placeholder'),
		array('icon-edsuitesigns' => 'icon-edsuitesigns'),
		array('icon-edsuitelinkedin-logo' => 'icon-edsuitelinkedin-logo'),
		array('icon-edsuitebook-with-white-bookmark2' => 'icon-edsuitebook-with-white-bookmark2'),
		array('icon-edsuitesigns3' => 'icon-edsuitesigns3'),
		array('icon-edsuitesigns4' => 'icon-edsuitesigns4'),
		array('icon-edsuitedialog' => 'icon-edsuitedialog'),
		array('icon-edsuiteelementary-school' => 'icon-edsuiteelementary-school'),
		array('icon-edsuitefacebook-letter-logo' => 'icon-edsuitefacebook-letter-logo'),
		array('icon-edsuitefacebook-logo-button' => 'icon-edsuitefacebook-logo-button'),
		array('icon-edsuitegoogle-plus' => 'icon-edsuitegoogle-plus'),
		array('icon-edsuitegoogle-plus-logo-button' => 'icon-edsuitegoogle-plus-logo-button'),
		array('icon-edsuitevimeo' => 'icon-edsuitevimeo'),
		array('icon-edsuiteinstagram-logo' => 'icon-edsuiteinstagram-logo'),
		array('icon-edsuiteinstagram-symbol' => 'icon-edsuiteinstagram-symbol'),
		array('icon-edsuiteknife-and-spoon-crossed' => 'icon-edsuiteknife-and-spoon-crossed'),
		array('icon-edsuitelong-arrow-pointing-to-the-right2' => 'icon-edsuitelong-arrow-pointing-to-the-right2'),
		array('icon-edsuitemortarboard' => 'icon-edsuitemortarboard'),
		array('icon-edsuitepinterest-circular-logo-symbol2' => 'icon-edsuitepinterest-circular-logo-symbol2'),
		array('icon-edsuitereading-sign' => 'icon-edsuitereading-sign'),
		array('icon-edsuiteright-arrow-thin' => 'icon-edsuiteright-arrow-thin'),
		array('icon-edsuiteright-arrow22' => 'icon-edsuiteright-arrow22'),
		array('icon-edsuiteright-arrow-in-black-circular-button' => 'icon-edsuiteright-arrow-in-black-circular-button'),
		array('icon-edsuiteright-arrow-signal' => 'icon-edsuiteright-arrow-signal'),
		array('icon-edsuiteright-chevron2' => 'icon-edsuiteright-chevron2'),
		array('icon-edsuitesocial-buttons-skype' => 'icon-edsuitesocial-buttons-skype'),
		array('icon-edsuitesocial-instagram-circle' => 'icon-edsuitesocial-instagram-circle'),
		array('icon-edsuitesocial-rss' => 'icon-edsuitesocial-rss'),
		array('icon-edsuitesocial-rss-circle-internet' => 'icon-edsuitesocial-rss-circle-internet'),
		array('icon-edsuitesocial-vimeo-in-a-circle-logo' => 'icon-edsuitesocial-vimeo-in-a-circle-logo'),
		array('icon-edsuitesuitcase' => 'icon-edsuitesuitcase'),
		array('icon-edsuitetarget-arrow' => 'icon-edsuitetarget-arrow'),
		array('icon-edsuitetelegram' => 'icon-edsuitetelegram'),
		array('icon-edsuitethin-right-arrow' => 'icon-edsuitethin-right-arrow'),
		array('icon-edsuitetime-almost-full' => 'icon-edsuitetime-almost-full'),
		array('icon-edsuitetrophy' => 'icon-edsuitetrophy'),
		array('icon-edsuitetwitter-black-shape' => 'icon-edsuitetwitter-black-shape'),
		array('icon-edsuitetwitter-logo-button' => 'icon-edsuitetwitter-logo-button'),
		array('icon-edsuiteuser' => 'icon-edsuiteuser'),
		array('icon-edsuiteyoutube-logo-play' => 'icon-edsuiteyoutube-logo-play'),
		array('icon-edsuiteyoutube-logo' => 'icon-edsuiteyoutube-logo'),
		array('icon-edsuiteyoutube-logotype' => 'icon-edsuiteyoutube-logotype'),
		array('icon-edsuiteic_check_box' => 'icon-edsuiteic_check_box'),
		array('icon-edsuiteic_star' => 'icon-edsuiteic_star'),
		array('icon-edsuiteic_notifications-bell' => 'icon-edsuiteic_notifications-bell'),
		array('icon-edsuiteic_notifications' => 'icon-edsuiteic_notifications'),
		array('icon-edsuiteic_people' => 'icon-edsuiteic_people'),
		array('icon-edsuiteic_person' => 'icon-edsuiteic_person'),
		array('icon-edsuiteic_poll' => 'icon-edsuiteic_poll'),
		array('icon-edsuiteic_public' => 'icon-edsuiteic_public'),
		array('icon-edsuiteic_school' => 'icon-edsuiteic_school'),
		array('icon-edsuitesocial-media3' => 'icon-edsuitesocial-media3'),
		array('icon-edsuiteic_event_note' => 'icon-edsuiteic_event_note'),
		array('icon-edsuiteic_phone_in_talk' => 'icon-edsuiteic_phone_in_talk'),
		array('icon-edsuiteic_arrow_back-one' => 'icon-edsuiteic_arrow_back-one'),
		array('icon-edsuiteic_arrow_drop_down' => 'icon-edsuiteic_arrow_drop_down'),
		array('icon-edsuiteic_arrow_drop_down_circle' => 'icon-edsuiteic_arrow_drop_down_circle'),
		array('icon-edsuiteic_arrow_drop_up' => 'icon-edsuiteic_arrow_drop_up'),
		array('icon-edsuitesigns-one' => 'icon-edsuitesigns-one'),
		array('icon-edsuiteic_arrow_forward' => 'icon-edsuiteic_arrow_forward'),
		array('icon-edsuitesmall-camera' => 'icon-edsuitesmall-camera'),
		array('icon-edsuitesocial' => 'icon-edsuitesocial'),
		array('icon-edsuitesocial-media' => 'icon-edsuitesocial-media'),
		array('icon-edsuitesocial-media1' => 'icon-edsuitesocial-media1'),
		array('icon-edsuitesocial-media2' => 'icon-edsuitesocial-media2'),
		array('icon-edsuitesymbol' => 'icon-edsuitesymbol'),
		array('icon-edsuitetelephone' => 'icon-edsuitetelephone'),
		array('icon-edsuitetime' => 'icon-edsuitetime'),
		array('icon-edsuitetime-one' => 'icon-edsuitetime-one'),
		array('icon-edsuitetime3' => 'icon-edsuitetime3'),
		array('icon-edsuitetool-one' => 'icon-edsuitetool-one'),
		array('icon-edsuitetool3' => 'icon-edsuitetool3'),
		array('icon-edsuiteic_arrow_upward' => 'icon-edsuiteic_arrow_upward'),
		array('icon-edsuiteic_check' => 'icon-edsuiteic_check'),
		array('icon-edsuiteic_chevron_left' => 'icon-edsuiteic_chevron_left'),
		array('icon-edsuiteic_chevron_right' => 'icon-edsuiteic_chevron_right'),
		array('icon-edsuiteic_beenhere' => 'icon-edsuiteic_beenhere'),
		array('icon-edsuiteic_directions_bus' => 'icon-edsuiteic_directions_bus'),
		array('icon-edsuiteic_local_dining' => 'icon-edsuiteic_local_dining'),
		array('icon-edsuiteic_local_library' => 'icon-edsuiteic_local_library'),
		array('icon-edsuiteic_local_printshop' => 'icon-edsuiteic_local_printshop'),
		array('icon-edsuiteic_person_pin' => 'icon-edsuiteic_person_pin'),
		array('icon-edsuiteic_pin_drop' => 'icon-edsuiteic_pin_drop'),
		array('icon-edsuiteic_place' => 'icon-edsuiteic_place'),
		array('icon-edsuiteic_assistant_photo' => 'icon-edsuiteic_assistant_photo'),
		array('icon-edsuiteic_burst_mode-one' => 'icon-edsuiteic_burst_mode-one'),
		array('icon-edsuiteic_collections_bookmark' => 'icon-edsuiteic_collections_bookmark'),
		array('icon-edsuiteic_color_lens-one' => 'icon-edsuiteic_color_lens-one'),
		array('icon-edsuiteic_photo_camera-one' => 'icon-edsuiteic_photo_camera-one'),
		array('icon-edsuiteic_photo_library' => 'icon-edsuiteic_photo_library'),
		array('icon-edsuiteic_picture_as_pdf' => 'icon-edsuiteic_picture_as_pdf'),
		array('icon-edsuiteic_portrait' => 'icon-edsuiteic_portrait'),
		array('icon-edsuiteic_slideshow' => 'icon-edsuiteic_slideshow'),
		array('icon-edsuiteic_folder' => 'icon-edsuiteic_folder'),
		array('icon-edsuiteic_attach_file' => 'icon-edsuiteic_attach_file'),
		array('icon-edsuiteic_format_quote' => 'icon-edsuiteic_format_quote'),
		array('icon-edsuiteic_format_size' => 'icon-edsuiteic_format_size'),
		array('icon-edsuiteic_insert_photo' => 'icon-edsuiteic_insert_photo'),
		array('icon-edsuiteic_add' => 'icon-edsuiteic_add'),
		array('icon-edsuiteic_add_circle' => 'icon-edsuiteic_add_circle'),
		array('icon-edsuiteic_flag' => 'icon-edsuiteic_flag'),
		array('icon-edsuiteic_link' => 'icon-edsuiteic_link'),
		array('icon-edsuiteic_email' => 'icon-edsuiteic_email'),
		array('icon-edsuiteic_forum' => 'icon-edsuiteic_forum'),
		array('icon-edsuiteic_import_contacts' => 'icon-edsuiteic_import_contacts'),
		array('icon-edsuiteic_message' => 'icon-edsuiteic_message'),
		array('icon-edsuiteic_phone' => 'icon-edsuiteic_phone'),
		array('icon-edsuiteic_ring_volume' => 'icon-edsuiteic_ring_volume'),
		array('icon-edsuiteic_equalizer' => 'icon-edsuiteic_equalizer'),
		array('icon-edsuiteic_library_add' => 'icon-edsuiteic_library_add'),
		array('icon-edsuiteic_library_books' => 'icon-edsuiteic_library_books'),
		array('icon-edsuiteic_play_arrow' => 'icon-edsuiteic_play_arrow'),
		array('icon-edsuiteic_play_circle_filled' => 'icon-edsuiteic_play_circle_filled'),
		array('icon-edsuiteic_subscriptions' => 'icon-edsuiteic_subscriptions'),
		array('icon-edsuiteic_video_library' => 'icon-edsuiteic_video_library'),
		array('icon-edsuiteic_videocam' => 'icon-edsuiteic_videocam'),
		array('icon-edsuiteic_volume_down' => 'icon-edsuiteic_volume_down'),
		array('icon-edsuiteic_accessibility' => 'icon-edsuiteic_accessibility'),
		array('icon-edsuiteic_account_balance' => 'icon-edsuiteic_account_balance'),
		array('icon-edsuiteic_account_balance_wallet-one' => 'icon-edsuiteic_account_balance_wallet-one'),
		array('icon-edsuiteic_account_box' => 'icon-edsuiteic_account_box'),
		array('icon-edsuiteic_account_circle' => 'icon-edsuiteic_account_circle'),
		array('icon-edsuiteic_assignment_ind' => 'icon-edsuiteic_assignment_ind'),
		array('icon-edsuiteic_bookmark' => 'icon-edsuiteic_bookmark'),
		array('icon-edsuiteic_class' => 'icon-edsuiteic_class'),
		array('icon-edsuiteic_date_range' => 'icon-edsuiteic_date_range'),
		array('icon-edsuiteic_favorite' => 'icon-edsuiteic_favorite'),
		array('icon-edsuiteic_question_answer' => 'icon-edsuiteic_question_answer'),
		array('icon-edsuiteic_record_voice_over' => 'icon-edsuiteic_record_voice_over'),
		array('icon-edsuiteic_room2' => 'icon-edsuiteic_room2'),
		array('icon-edsuiteic_schedule' => 'icon-edsuiteic_schedule'),
		array('icon-edsuiteic_search' => 'icon-edsuiteic_search'),
		array('icon-edsuiteic_settings_phone' => 'icon-edsuiteic_settings_phone'),
		array('icon-edsuiteic_speaker_notes' => 'icon-edsuiteic_speaker_notes'),
		array('icon-edsuiteic_stars' => 'icon-edsuiteic_stars'),
		array('icon-edsuiteic_supervisor_account' => 'icon-edsuiteic_supervisor_account'),
		array('icon-edsuiteic_thumb_up' => 'icon-edsuiteic_thumb_up'),
		array('icon-edsuiteic_today' => 'icon-edsuiteic_today'),
		array('icon-edsuiteic_trending_down' => 'icon-edsuiteic_trending_down'),
		array('icon-edsuiteic_trending_flat-one' => 'icon-edsuiteic_trending_flat-one'),
		array('icon-edsuiteic_turned_in' => 'icon-edsuiteic_turned_in'),
		array('icon-edsuiteic_verified_user' => 'icon-edsuiteic_verified_user'),
		array('icon-edsuiteic_visibility' => 'icon-edsuiteic_visibility'),
		array('icon-edsuiteic_watch_later' => 'icon-edsuiteic_watch_later'),
		array('icon-edsuiteic_zoom_in' => 'icon-edsuiteic_zoom_in'),
		array('icon-edsuitedown-chevron-down' => 'icon-edsuitedown-chevron-down'),
		array('icon-edsuitetwo-quotes' => 'icon-edsuitetwo-quotes'),



	);

	return $theme_icons;
}